### ISSUE TITLE
Pokemon attack speed

### ISSUE THREAD

**Issue by Derpenheim** [renlok/renlok.github.io#11]
The attack speed of wild pokemon is so drastically high (and unrepresentative of how often they attack) that I have trouble with pokemon that are tens of levels below me. My pokemon slow down enormously as they level, rather than maintaining speed and losing it when they evolve into more defense oriented pokemon (Pikachu evolving into raichu, for example). This makes it nearly impossible for a level 20 rattata to beat more than 3 or 4 level 5 rattatas before fainting. Further, a caterpie that has 1.173 attack speed will attack 4 to 5 times for every 1 attack my jigglypuff with 1.157 attack speed makes.

UPDATE: I refreshed the page, it seemed to fix it, but the issue came back. Something in the code is having some sort of caching error, or some amount of pile up that is causing attack queues to stack far faster than they should.

**Comment by renlok** [comment]
The attack speed is the number of seconds between attacks so it goes down as they level. I should probably rename it to something else.

And there was a problem in the past with the attack speed being super messed up but I thought I fixed it. Maybe you had an old version loaded from your cache.

For me it seems like my pokemon are attacking way too fast. Even at level 40 they attack crazy fast

**Comment by Derpenheim** [comment]
I realized a while later about the attack speed, I was just confused by the weird thing happening. It seems to happen most when I switch between routes, suddenly they'll attack 4-5 times in 1 of my attacks, but a refresh solves that. And I found this game last night, so I dont think its an old version issue.

**Comment by renlok** [comment]
I think I've found and fixed what you meant now let me know.

**Comment by Derpenheim** [comment]
Seems totally fixed, I can't even replicate the issue on purpose. Whatever you did, works great. Thanks.
